# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "C-MOOR Tutorials"
license = "MIT"
licenselink = "https://github.com/KatherineCox/experimenting-with-hugo/blob/main/themes/cmoor-tutorials/LICENSE"
description = ""
homepage = "https://github.com/KatherineCox/experimenting-with-hugo"
tags = []
features = []
min_version = "0.92.0"

[author]
  name = "Katherine Cox"
  homepage = "https://github.com/KatherineCox"
